### ISSUE TITLE
Add effect sizes to output

### ISSUE THREAD

**Issue by ddauber** [IndrajeetPatil/statsExpressions#123]
I was wondering how hard it would be to include the effect size right after the column that indicates the type of effect size used. It is already available for the plots, but not in the tibble?

Thanks for considering it 😉

**Comment by IndrajeetPatil** [comment]
Hi, 

The effect sizes and their confidence intervals are already included in the tibble under the columns estimate, conf.low, and conf.high.

**Comment by ddauber** [comment]
Found it. Thanks. It was not quite apparent on first sight that the 'estimate' actually refers to the effectsize. Clarified it 👍

**Comment by IndrajeetPatil** [comment]
Hmm, good point.

Maybe I should move the effect size name column before estimate. Will do so in the next release.

**Comment by ddauber** [comment]
I wondered whether the following naming convention could help:

'effsize' for the estimate
'effsize_type' for the name of it. 

Just pure cosmetics, but potentially more intuitive. 

Great work with this package. 👍
