### ISSUE TITLE
Error in two_sample_test(type = "np")

### ISSUE THREAD

**Issue by ddauber** [IndrajeetPatil/statsExpressions#124]
I used the example below from your [website](https://indrajeetpatil.github.io/statsExpressions/reference/two_sample_test.html).

According to the underlying function `statistics` is supposed to be `25.5`. Also, your example on the website produces a `statistic = 25.5`. 

However, when running it in my R session, it returns `statistics = 3.238678`, while the underlying test does return the correct statistic.

Looks like a bug and should be an easy fix, I guess.

``` r
library(tidyverse)
library(statsExpressions)

two_sample_test(
  data = sleep,
  x = group,
  y = extra,
  type = "np"
) %>% glimpse()
#> Rows: 1
#> Columns: 13
#> $ parameter1  <chr> "extra"
#> $ parameter2  <chr> "group"
#> $ statistic   <dbl> 3.238678
#> $ p.value     <dbl> 0.06932758
#> $ method      <chr> "Wilcoxon rank sum test"
#> $ alternative <chr> "two.sided"
#> $ estimate    <dbl> -0.49
#> $ conf.level  <dbl> 0.95
#> $ conf.low    <dbl> -0.7835953
#> $ conf.high   <dbl> -0.01750082
#> $ effectsize  <chr> "r (rank biserial)"
#> $ conf.method <chr> "normal"
#> $ expression  <list> <paste("log"["e"](italic("W")["Mann-Whitney"]), " = ", "3.…

wilcox.test(extra ~ group,
            data = sleep,
            correct = FALSE,
            alternative = "two.sided")
#> Warning in wilcox.test.default(x = c(0.7, -1.6, -0.2, -1.2, -0.1, 3.4, 3.7, :
#> cannot compute exact p-value with ties
#> 
#>  Wilcoxon rank sum test
#> 
#> data:  extra by group
#> W = 25.5, p-value = 0.06372
#> alternative hypothesis: true location shift is not equal to 0
```

**Comment by ddauber** [comment]
I tried to reproduce some of your examples from the website. It appears that the same problem applies to the paired version of the non-parametric test.

``` r
library(tidyverse)
library(statsExpressions)

two_sample_test(
  data = dplyr::filter(bugs_long, condition %in% c("HDHF", "HDLF")),
  x = condition,
  y = desire,
  paired = TRUE,
  subject.id = subject,
  type = "np"
)
#> # A tibble: 1 × 13
#>   parameter1 parameter2 statistic  p.value method alternative estimate conf.level
#>   <chr>      <chr>          <dbl>    <dbl> <chr>  <chr>          <dbl>      <dbl>
#> 1 desire     condition       7.49 0.000430 Wilco… two.sided      0.487       0.95
#> # … with 5 more variables: conf.low <dbl>, conf.high <dbl>, effectsize <chr>,
#> #   conf.method <chr>, expression <list>
```

The statistic is supposed to be `1796`, but it shows as `7.49` when run in my R session:

The problem appears to be limited to 'np' tests only since I could reproduce the examples for the parametric tests. Btw, all other statistics reported seem fine.

Hope that helps to pinpoint the bug.

**Comment by IndrajeetPatil** [comment]
Hi, this discrepancy is due to the fact that:

- **CRAN version** uses log value of statistic for non-parametric tests

- The website is for **development version on GitHub** that has changed this behavior and now no longer shows log value of statistic 

So once this development version is submitted to CRAN, you will see similar results.

**Comment by ddauber** [comment]
Thanks for the fast reply.
