### ISSUE TITLE
Exact p-value calculation using Wilcoxon rank sum test

### ISSUE THREAD

**Issue by Aashilbatavia** [IndrajeetPatil/statsExpressions#191]
Hello, 

I was wondering how you obtain an exact p-value when applying a wilcoxon-rank i.e how do you go around the issues of ties (which i get when I apply the test manually. 

Thanks

**Comment by IndrajeetPatil** [comment]
Hi, sorry for the late reply.

From the next version, `extract` argument will be set to `FALSE`. It was negligence on my part that it already wasn't.
