### ISSUE TITLE
i wonder if `pairwise_comparisons` can do Tukey's HSD?

### ISSUE THREAD

**Issue by the8thday** [IndrajeetPatil/statsExpressions#243]
Hi,
i wonder if Tukey's HSD can added to the `pairwise_comparisons` function, as i can not find it in the `p.adjust.method` parameter.

Thank you so much!

**Comment by IndrajeetPatil** [comment]
No, unfortunately, this is not possible. 

Currently, only one type of statistical test is supported per type of statistical approach, and Tukey's HSD is not one of them.
