### ISSUE TITLE
Install failed: "Error: object 'wmcpAKP' is not exported by 'namespace:WRS2'"

### ISSUE THREAD

**Issue by sbibauw** [IndrajeetPatil/statsExpressions#91]
When trying to install `statsExpressions` (with `ggstatsplot`), I systematically get this error and do not find how to circumvent it.

```r
remotes::install_github(repo = "IndrajeetPatil/statsExpressions",  dependencies = FALSE, quick = TRUE)
OR
install.packages("ggstatsplot")

Installing package into '/Users/me/Library/R/4'
(as 'lib' is unspecified)
* installing *source* package 'statsExpressions' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Error: object 'wmcpAKP' is not exported by 'namespace:WRS2'
Execution halted
ERROR: lazy loading failed for package 'statsExpressions'
* removing '/Users/me/Library/R/4/statsExpressions'
* restoring previous '/Users/me/Library/R/4/statsExpressions'
```

(Note: a similar error message has also been reported [here](https://community.rstudio.com/t/ggstatsplot-error-package-or-namespace-load-failed-for-ggstatsplot-object-wmcpakp-is-not-exported-by-namespace-wrs2/101931))

**Comment by IndrajeetPatil** [comment]
You just need to update `WRS2` to the latest `CRAN` version (`1.1-1`) and this should go away.

😉  cf. https://yihui.org/en/2017/05/when-in-doubt-upgrade/

**Comment by sbibauw** [comment]
Thanks, indeed, it solved the problem. Sorry for not having thought of it (I actually didn't realize WRS2 was another package, which sounds obvious now that you said it).
